/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnlsEncargado;

import MisPaquetes.Empresa;
import MisPaquetes.Oferta;
import MisPaquetes.Producto;
import MisPaquetes.Sucursal;
import Sistema.Administrador.Empresa_List;
import static Sistema.MainSistema.conn;
import java.awt.event.KeyEvent;
import java.io.*;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.serial.SerialBlob;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import oracle.sql.BLOB;

/**
 *
 * @author 
 */
public class pnlOfertas extends javax.swing.JPanel {
    
    JFileChooser seleccionado = new JFileChooser();
    File archivo = null;
    byte[] bytesImg;

    /**
     * Creates new form pnlHome
     */
    public pnlOfertas() {
        try {
            initComponents();
            cargarTabla();
            cargarComboBox();
            vistaDefault();
        } catch (SQLException ex) {
            Logger.getLogger(pnlOfertas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarImagen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaOfertas = new javax.swing.JTable();
        pnlOferta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescr = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cldFechaInicio = new com.toedter.calendar.JDateChooser();
        ddlSucursal = new javax.swing.JComboBox<>();
        ddlProducto = new javax.swing.JComboBox<>();
        cldFechaTermino = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtValoracion = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        pnlBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblRespuestaBuscar = new javax.swing.JLabel();
        javax.swing.JButton btnNewOferta = new javax.swing.JButton();
        lblRespuestaOferta = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBuscarImagen.setText("Buscar imagen");
        btnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lblImagen);

        tablaOfertas.setBackground(new java.awt.Color(240, 240, 240));
        tablaOfertas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaOfertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaOfertasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaOfertas);

        pnlOferta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3), "Oferta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Descripcion:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Termino:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valoracion Total:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sucursal: ");

        txtDescr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescrKeyTyped(evt);
            }
        });

        txtDescuento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID Oferta");

        txtId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Producto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Inicio:");

        ddlSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la sucursal" }));

        ddlProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el producto" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("% Descuento:");

        txtValoracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValoracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValoracionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlOfertaLayout = new javax.swing.GroupLayout(pnlOferta);
        pnlOferta.setLayout(pnlOfertaLayout);
        pnlOfertaLayout.setHorizontalGroup(
            pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOfertaLayout.createSequentialGroup()
                        .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cldFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))
                    .addGroup(pnlOfertaLayout.createSequentialGroup()
                        .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlOfertaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOfertaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ddlSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addGap(43, 43, 43)
                        .addComponent(ddlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlOfertaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlOfertaLayout.setVerticalGroup(
            pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cldFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ddlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        pnlBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3), "Búsqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscar.setText("Ingrese ID de Oferta");
        txtBuscar.setToolTipText("");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar)
                .addContainerGap())
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnBuscar)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addContainerGap())
        );

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblRespuestaBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRespuestaBuscar.setForeground(java.awt.Color.red);
        lblRespuestaBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRespuestaBuscar.setText("Respuesta");

        btnNewOferta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNewOferta.setText("Nuevo Producto");
        btnNewOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOfertaActionPerformed(evt);
            }
        });

        lblRespuestaOferta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRespuestaOferta.setForeground(java.awt.Color.red);
        lblRespuestaOferta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRespuestaOferta.setText("Respuesta");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscarImagen)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRespuestaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnNewOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36))
                        .addComponent(jScrollPane3)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(181, 181, 181)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRespuestaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnBuscarImagen)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRespuestaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNewOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblRespuestaBuscar)
                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        // TODO add your handling code here:
        if (seleccionado.showDialog(this, "Abrir Archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")) {
                    bytesImg = cargarImagen(archivo);
                    lblImagen.setIcon(new ImageIcon(bytesImg));
                }else{
                    JOptionPane.showMessageDialog(null, "Por favor ingrese una imagen");
                }
                
            }
        }
    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void tablaOfertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaOfertasMouseClicked
        int seleccion = tablaOfertas.getSelectedRow();
        int idSelect = (int) tablaOfertas.getModel().getValueAt(seleccion, 0);
        txtBuscar.setText(String.valueOf(idSelect));
        buscarOferta();
    }//GEN-LAST:event_tablaOfertasMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            Oferta ofer = new Oferta();
            ofer.setDescripcion(txtDescr.getText());
            java.util.Date utilDate = (java.util.Date) cldFechaInicio.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            ofer.setFecha_inicio(sqlDate);
            utilDate = (java.util.Date) cldFechaTermino.getDate();
            sqlDate = new java.sql.Date(utilDate.getTime());
            ofer.setFecha_termino(sqlDate);
            /*Blob blob;
            try {
                FileInputStream archiv2  = new FileInputStream(archivo);
                ofer.setImagen(archiv2);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(pnlOfertas.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            ofer.setImagen(bytesImg);
            /*
            try {
               blob = new oracle.sql.BLOB(bytesImg);
               // ofer.setImagen(archiv2);
            } catch (SQLException ex) {
             Logger.getLogger(pnlOfertas.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            
            ofer.setValoracion_total(Integer.parseInt(txtValoracion.getText()));
            ofer.setPorc_descuento(Integer.parseInt(txtDescuento.getText()));
            int respuesta = 0;
            Sucursal su =  new Sucursal();
            if (ddlSucursal.getSelectedIndex() != 0) {
                su = (Sucursal) ddlSucursal.getModel().getSelectedItem();
                ofer.setId_sucursal(su.getId_sucur());
            }
            if (ddlSucursal.getSelectedIndex() == 0) {
                //throw new Exception ("Falta Seleccionar la Sucursal");
            }
            if (ddlProducto.getSelectedIndex() == 0) {
                //throw new Exception ("Falta Seleccionar el producto");
            }
            if (archivo == null) {
                //throw new Exception ("Debe seleccionar una imagen");
            }
            Producto pro = new Producto();
            if (ddlProducto.getSelectedIndex() != 0) {
                pro = (Producto) ddlProducto.getModel().getSelectedItem();
                ofer.setId_producto(pro.getId());
            }  
            
            if (txtDescr.isEnabled()) {
                int a = JOptionPane.showConfirmDialog(null, "¿Desea Registrar esta oferta?", "Message",  JOptionPane.YES_NO_OPTION);
                if (a == 0 ) {
                    respuesta = ofer.agregar(conn);
                    if(respuesta == 1){
                        JOptionPane.showMessageDialog(null,"La oferta fue registrada",null, JOptionPane.INFORMATION_MESSAGE, null);
                        try {
                            cargarTabla();
                            vistaDefault();
                        } catch (SQLException ex) {
                            Logger.getLogger(pnlOfertas.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"La oferta ya fue registrada",null, JOptionPane.INFORMATION_MESSAGE, null);
                    }
                }

            }
            
            
           
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"" + ex.getMessage(),null, JOptionPane.INFORMATION_MESSAGE, null);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vistaDefault();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //buscarProducto();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        txtDescr.setEnabled(false);
        txtDescuento.setEnabled(true);
        ddlSucursal.setEnabled(true);
        txtValoracion.setEnabled(true);
        ddlProducto.setEnabled(true);
        txtDescuento.setEnabled(true);
        cldFechaInicio.setEnabled(true);
        cldFechaTermino.setEnabled(true);
        btnBuscarImagen.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNewOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOfertaActionPerformed
        vistaDefault();
        txtDescr.setEnabled(true);
        txtDescuento.setEnabled(true);
        ddlSucursal.setEnabled(true);
        txtValoracion.setEnabled(true);
        txtDescuento.setEnabled(true);
        ddlProducto.setEnabled(true);
        cldFechaInicio.setEnabled(true);
        cldFechaTermino.setEnabled(true);
        btnBuscarImagen.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtDescr.requestFocus();
    }//GEN-LAST:event_btnNewOfertaActionPerformed

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        // TODO add your handling code here:
        if(txtDescuento.getText().length()>= 200){
            evt.consume();
        }
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void txtDescrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescrKeyTyped
        // TODO add your handling code here:
        if(txtDescr.getText().length()>=25){
            evt.consume();
        }
    }//GEN-LAST:event_txtDescrKeyTyped

    private void txtValoracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValoracionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValoracionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private com.toedter.calendar.JDateChooser cldFechaInicio;
    private com.toedter.calendar.JDateChooser cldFechaTermino;
    private javax.swing.JComboBox<Object> ddlProducto;
    private javax.swing.JComboBox<Object> ddlSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblRespuestaBuscar;
    private javax.swing.JLabel lblRespuestaOferta;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlOferta;
    private javax.swing.JTable tablaOfertas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescr;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtValoracion;
    // End of variables declaration//GEN-END:variables

    private byte[] cargarImagen(File archivo) {
        FileInputStream entrada;
        FileOutputStream salida;
        Long i = archivo.length();
        Integer tam = i.intValue();
        byte[] byteImg = new byte[tam];
        try{
            entrada = new FileInputStream(archivo);
            entrada.read(byteImg);
        } catch (Exception e){
            
        }
        return byteImg;
    }

    private void cargarTabla() throws SQLException{
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("Inicio");
        modelo.addColumn("Termino");

        Oferta ofer = new Oferta();
        ResultSet rs = ofer.listadoOfertas(conn);
        Object[] fila = new Object[6];
        while (rs.next()) {
            fila[0] = rs.getInt("ID_OFERTA");
            fila[1] = rs.getString("DESCRIPCION");
            fila[2] = rs.getDate("FEC_INICIO");
            fila[3] = rs.getDate("FEC_TERMINO");
            modelo.addRow(fila);
        }
        tablaOfertas.setModel(modelo);
        tablaOfertas.setVisible(true);
    }

    private void cargarComboBox() throws SQLException{
        Sucursal suc = new Sucursal();
        ResultSet rs = suc.listadoSucursales(conn);
        while (rs.next()) {
            Sucursal v_suc = new Sucursal();
            v_suc.setId_sucur(rs.getInt("ID_SUCUR"));
            v_suc.setNombre(rs.getString("NOMBRE"));
            v_suc.setFono(rs.getString("FONO"));
            v_suc.setDireccion(rs.getString("DIRECCION"));
            v_suc.setComuna(rs.getString("COMUNA"));
            v_suc.setEmpresaRut(rs.getString("EMPRESA_RUT"));
            ddlSucursal.addItem(v_suc);
        }
        
        Producto pro = new Producto();
        ResultSet rs1 = pro.listadoProductos(conn);
        while (rs1.next()) {
            Producto v_pro = new Producto();
            v_pro.setId(rs1.getInt("ID_PROD"));
            v_pro.setNombre(rs1.getString("NOMBRE"));
            v_pro.setDescripcion(rs1.getString("DESC_PROD"));
            v_pro.setFecha_ing(rs1.getDate("FEC_INGRESO"));
            v_pro.setEstado(rs1.getString("ESTADO").charAt(0));
            v_pro.setStk_seguro(rs1.getInt("STK_SEGURO"));
            v_pro.setRubro(rs1.getString("RUBRO"));
            v_pro.setDesc_rubro(rs1.getString("DESC_RUBRO"));
            v_pro.setValor(rs1.getInt("VALOR"));
            ddlProducto.addItem(v_pro);
        }
        
        
        
    }

    private void vistaDefault(){
        txtDescr.setEnabled(false);
        txtValoracion.setEnabled(false);
        ddlSucursal.setEnabled(false);
        ddlProducto.setEnabled(false);
        cldFechaInicio.setEnabled(false);
        cldFechaTermino.setEnabled(false);
        btnBuscarImagen.setEnabled(false);
        txtDescuento.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        txtDescr.setText("");
        txtDescuento.setText("");
        ddlSucursal.setSelectedIndex(0);
        ddlProducto.setSelectedIndex(0);
        txtId.setText("");
        txtBuscar.setText("Ingrese ID de la oferta");
        lblRespuestaBuscar.setText("");
        lblRespuestaOferta.setText("");
    }

    private void buscarOferta() {
        Oferta ofer = new Oferta();
        ofer = ofer.buscar(Integer.parseInt(txtBuscar.getText()), conn);
        if(!ofer.getDescripcion().equals("ERROR")){
            vistaDefault();
            txtBuscar.setText(String.valueOf(ofer.getId()));
            txtId.setText(String.valueOf(ofer.getId()));
            txtDescr.setText(ofer.getDescripcion());
            txtValoracion.setText(String.valueOf(ofer.getValoracion_total()));
            txtDescuento.setText(String.valueOf(ofer.getPorc_descuento()));
            cldFechaInicio.setDate(ofer.getFecha_inicio());
            cldFechaTermino.setDate(ofer.getFecha_termino());
            ddlSucursal.setSelectedItem(ofer.getId_sucursal());
            ddlProducto.setSelectedItem(ofer.getId_producto());
            lblImagen.setIcon(new ImageIcon(ofer.getImagen()));
            
            
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }else if(txtDescr.getText().equals("Ingrese ID de la oferta")){
            vistaDefault();
            lblRespuestaBuscar.setText("Ingrese ID antes de Buscar");
        }else{
            lblRespuestaBuscar.setText("No hay registros de la oferta con ID: " + txtBuscar.getText());
            vistaDefault();
        }
    }
    
    
}
