/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnlsAdministrador;

import pnlsEncargado.*;
import MisPaquetes.Empresa;
import MisPaquetes.Producto;
import MisPaquetes.Sucursal;
import static Sistema.MainSistema.conn;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class pnlProductos extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlProductos() {
        try {
            initComponents();
            cargarTabla();
            vistaDefault();
            cargarEmpresas();
        } catch (SQLException ex) {
            Logger.getLogger(pnlProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewProducto = new javax.swing.JButton();
        lblRespuestaBuscar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        pnlBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pnlProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtSeguro = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblRespuestaEmpresa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        ddlEstado = new javax.swing.JComboBox<>();
        ddlRubro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtStockSucur = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ddlEmpresa2 = new javax.swing.JComboBox<>();
        ddlSucursal2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductos2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnNewProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNewProducto.setText("Nuevo Producto");
        btnNewProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductoActionPerformed(evt);
            }
        });

        lblRespuestaBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRespuestaBuscar.setForeground(java.awt.Color.red);
        lblRespuestaBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRespuestaBuscar.setText("Respuesta");

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        pnlBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3), "Búsqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscar.setText("Ingrese ID de Producto");
        txtBuscar.setToolTipText("");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(155, 155, 155))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        pnlProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3), "Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Ingreso");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Estado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Stock Seguro:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        txtSeguro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeguroKeyTyped(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID Producto");

        txtId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rubro:");

        lblRespuestaEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRespuestaEmpresa.setForeground(java.awt.Color.red);
        lblRespuestaEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRespuestaEmpresa.setText("Respuesta");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Descripción");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Valor:");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        txtFechaIngreso.setMaxSelectableDate(new java.util.Date(4102459296000L));
        txtFechaIngreso.setMinSelectableDate(new java.util.Date(-2208968138000L));

        ddlEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Fuera De Temporada", "Vencido" }));

        ddlRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el rubro", "Alimento", "Electronica", "Linea Blanca", "Vestuario", "Calzado" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Stock sucursal:");
        jLabel10.setToolTipText("");

        txtStockSucur.setMinimumSize(new java.awt.Dimension(6, 23));
        txtStockSucur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockSucurKeyTyped(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)), "Lugar de Trabajo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        ddlEmpresa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ddlEmpresa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la empresa" }));
        ddlEmpresa2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddlEmpresa2ItemStateChanged(evt);
            }
        });

        ddlSucursal2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ddlSucursal2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Sucursal" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Empresa");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Sucursal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ddlEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ddlSucursal2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(117, 117, 117))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddlEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlSucursal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18))))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ddlRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStockSucur, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(lblRespuestaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ddlRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtStockSucur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRespuestaEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductoLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tablaProductos2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaProductos2.setBackground(new java.awt.Color(240, 240, 240));
        tablaProductos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaProductos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductos2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaProductos2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(lblRespuestaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblRespuestaBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlProducto.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funcion que activa los campos de texto de un producto
     * @param evt Evento de presionar el boton agregar
     */
    private void btnNewProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductoActionPerformed
        vistaDefault();
        txtNombre.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtFechaIngreso.setEnabled(true);
        txtSeguro.setEnabled(true);
        txtStockSucur.setEnabled(true);
        ddlRubro.setEnabled(true);
        
        ddlEmpresa2.setEnabled(true);
        ddlSucursal2.setEnabled(true);
        
        txtValor.setEnabled(true);
        ddlEstado.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnNewProducto.setEnabled(false);
        txtNombre.requestFocus();
        
    }//GEN-LAST:event_btnNewProductoActionPerformed

    /**
     * Funcion que activa los campos de texto de un producto
     * @param evt Evento de presionar el boton agregar
     */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        txtNombre.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtFechaIngreso.setEnabled(true);
        txtSeguro.setEnabled(true);
        txtStockSucur.setEnabled(true);
        ddlRubro.setEnabled(true);
        ddlEstado.setEnabled(true);
        ddlEmpresa2.setEnabled(true);
        ddlSucursal2.setEnabled(true);
        txtValor.setEnabled(true);
        
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnNewProducto.setEnabled(false);
        btnAgregar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * Funcion que limpia el campo de texto para buscar producto por ID 
     * @param evt Evento de presionar el boton buscar
     */
    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    /**
     * Funcion que se activa al momento de presionar el boton buscar
     * @param evt Evento que se activa al momento de presionar el boton buscar
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarProducto();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Funcion que elimina un producto por ID
     * @param evt Evento de presionar el boton eliminar
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Producto pro = new Producto();
        pro.setId(Integer.parseInt(txtId.getText()));
        int respuesta = 0;
        int a = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar este Producto?", "Message",  JOptionPane.YES_NO_OPTION);
        if(a == 0){
            respuesta = pro.eliminar(conn);
            if(respuesta == 1){
                JOptionPane.showMessageDialog(null,"El producto fue Eliminado",null, JOptionPane.INFORMATION_MESSAGE, null);
                try {
                    cargarTabla();
                    vistaDefault();
                } catch (SQLException ex) {
                    Logger.getLogger(pnlProductos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Error al Eliminar",null, JOptionPane.INFORMATION_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Funcion que agrega o modifica un producto 
     * @param evt Evento de presionar el boton agregar
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            if (!validadorCampos()){
                throw new Exception ("Ingrese todos los datos");
            }
            Producto pro = new Producto();
            pro.setNombre(txtNombre.getText());
            pro.setDescripcion(txtDescripcion.getText());
            java.util.Date utilDate = (java.util.Date) txtFechaIngreso.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            pro.setFecha_ing(sqlDate);
            char estado = cargarEstado();
            pro.setEstado(estado);
            if (!validarStock(Integer.parseInt(txtSeguro.getText()))) {
                throw new Exception ("El stock seguro no puede ser negativo");
            }
            pro.setStk_seguro(Integer.parseInt(txtSeguro.getText()));
            pro.setStk_sucur(Integer.parseInt(txtStockSucur.getText()));
            pro.setRubro(obtenerRubro());
            pro.setDesc_rubro(obtenerDescRubro());
            if (!validarValor(Integer.parseInt(txtValor.getText()))) {
                throw new Exception ("El stock seguro no puede ser negativo");
            }
            pro.setValor(Integer.parseInt(txtValor.getText()));
            //Sera cambiado 
            try{
                Sucursal suc = (Sucursal)ddlSucursal2.getModel().getSelectedItem();
                pro.setId_sucur(suc.getId_sucur());
            }catch(Exception e){
                
            }
            int respuesta = 0;
        
            if (txtId.getText().equals("")) {
                int a = JOptionPane.showConfirmDialog(null, "¿Desea Registrar este producto?", "Message",  JOptionPane.YES_NO_OPTION);
                if (a == 0 ) {
                    respuesta = pro.agregar(conn);
                    if(respuesta == 1){
                        JOptionPane.showMessageDialog(null,"El producto fue registrado",null, JOptionPane.INFORMATION_MESSAGE, null);
                        try {
                            cargarTabla();
                            vistaDefault();
                        } catch (SQLException ex) {
                            Logger.getLogger(pnlProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"El Producto ya fue registrado",null, JOptionPane.INFORMATION_MESSAGE, null);
                    }
                }
            }else{
                int a = JOptionPane.showConfirmDialog(null, "¿Desea Modificar este Producto?", "Message",  JOptionPane.YES_NO_OPTION);
                if(a == 0){
                    pro.setId(Integer.parseInt(txtId.getText()));
                    respuesta = pro.modificar(conn);
                    if(respuesta == 1){
                        JOptionPane.showMessageDialog(null,"El Producto fue Modificado",null, JOptionPane.INFORMATION_MESSAGE, null);
                        try {
                            cargarTabla();
                            vistaDefault();
                        } catch (SQLException ex) {
                            Logger.getLogger(pnlProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Ocurrio un error al Modificar",null, JOptionPane.INFORMATION_MESSAGE, null);
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"" + ex.getMessage(),null, JOptionPane.INFORMATION_MESSAGE, null);
        } 
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Funcion que cancela la operacion que se este realizando en el momento
     * @param evt Evento de presionar el boton cancelar
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vistaDefault();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Funcion que busca un producto seleccionado en la tabla de productos
     * @param evt Evento de seleccionar un elemento de la tabla 
     */
    private void tablaProductos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductos2MouseClicked
        int seleccion = tablaProductos2.getSelectedRow();
        int idSelect = (int) tablaProductos2.getModel().getValueAt(seleccion, 0);
        txtBuscar.setText(String.valueOf(idSelect));
        buscarProducto();
    }//GEN-LAST:event_tablaProductos2MouseClicked

    /**
     * Restriccion de caracteres, solo numericos para el campo de texto de stock seguro
     * @param evt Evento de presionar una tecla
     */
    private void txtSeguroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguroKeyTyped
        // TODO add your handling code here: 
        char caracter = evt.getKeyChar();
        if(((caracter < '0') || 
        (caracter > '9')) &&
        (caracter != KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        if(txtSeguro.getText().length()>= 7){
            evt.consume();
        }

    }//GEN-LAST:event_txtSeguroKeyTyped

    /**
     * Restriccionar de cantidad de caracteres para el campo de texto de nombre de producto
     * @param evt Evento de presionar una tecla
     */
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        if(txtNombre.getText().length()>=25){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * Restriccionar de cantidad de caracteres para el campo de texto de nombre de descripcion
     * @param evt Evento de presionar una tecla
     */
    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
        if(txtDescripcion.getText().length()>= 200){
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    /**
     * Restriccion de caracteres, solo numericos para el campo de texto de valor de producto
     * @param evt Evento de presionar una tecla
     */
    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(((caracter < '0') || 
        (caracter > '9')) &&
        (caracter != KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        
        if(txtValor.getText().length()>= 9){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    /**
     * Restriccion de caracteres, solo numericos para el campo de texto de stock en sucursal
     * @param evt Evento de presionar una tecla
     */
    private void txtStockSucurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockSucurKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(((caracter < '0') || 
        (caracter > '9')) &&
        (caracter != KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        
        if(txtValor.getText().length()>= 9){
            evt.consume();
        }
    }//GEN-LAST:event_txtStockSucurKeyTyped

    private void ddlEmpresa2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddlEmpresa2ItemStateChanged
        if (ddlEmpresa2.getSelectedIndex() != 0) {
            Empresa emp = (Empresa) ddlEmpresa2.getModel().getSelectedItem();
            try {
                cargarSucursales(emp.getRut());
            } catch (SQLException ex) {
                Logger.getLogger(pnlUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ddlSucursal2.removeAllItems();
            ddlSucursal2.addItem("Seleccione la Sucursal");
        }
    }//GEN-LAST:event_ddlEmpresa2ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNewProducto;
    private javax.swing.JComboBox<Object> ddlEmpresa2;
    private javax.swing.JComboBox<String> ddlEstado;
    private javax.swing.JComboBox<String> ddlRubro;
    private javax.swing.JComboBox<Object> ddlSucursal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblRespuestaBuscar;
    private javax.swing.JLabel lblRespuestaEmpresa;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTable tablaProductos2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeguro;
    private javax.swing.JTextField txtStockSucur;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    /**
     * Carga de la tabla inferior correspondiente al listado de productos que
     * que se encuentra en la base de datos
     * @throws SQLException 
     */
    private void cargarTabla() throws SQLException {
        DefaultTableModel modelo =  new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            
            Producto pro = new Producto();
            ResultSet rs = pro.listadoProductos(conn);
            Object [] fila = new Object[6];
            while(rs.next()){
                fila[0] = rs.getInt("ID_PROD");
                fila[1] = rs.getString("NOMBRE");
                modelo.addRow(fila);
            }
            
            
            tablaProductos2.setModel(modelo);
            tablaProductos2.setVisible(true);
    }

    /**
     *Los campos de texto para agregar cada inhabilitados
     * Los campos de texto quedan seteados con cadenas vacias
     */
    private void vistaDefault() {
        
        txtNombre.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtFechaIngreso.setEnabled(false);
        txtSeguro.setEnabled(false);
        txtStockSucur.setEnabled(false);
        ddlRubro.setEnabled(false);
        ddlEstado.setEnabled(false);
        txtValor.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnCancelar.setEnabled(false);
        ddlEmpresa2.setEnabled(false);
        ddlSucursal2.setEnabled(false);
        ddlSucursal2.removeAllItems();
        ddlSucursal2.addItem("Seleccione la Sucursal");
        btnNewProducto.setEnabled(true);
        
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtSeguro.setText("");
        txtStockSucur.setText("");
        ddlRubro.setSelectedIndex(0);
        txtValor.setText("");
        txtId.setText("");
        ddlEmpresa2.setSelectedIndex(0);
        ddlSucursal2.setSelectedIndex(0);
        txtBuscar.setText("Ingrese ID del producto");
        lblRespuestaBuscar.setText("");
        lblRespuestaEmpresa.setText("");
    }

    /**
     * Funcion que busca un producto en la base de datos por id 
     * Luego de encontrado el producto se despliegan sus datos en los campos de texto
     */
    private void buscarProducto() {
        Producto pro = new Producto();
        pro = pro.buscar(Integer.parseInt(txtBuscar.getText()), conn);
        if(!pro.getNombre().equals("ERROR")){
            vistaDefault();
            txtBuscar.setText(String.valueOf(pro.getId()));
            txtId.setText(String.valueOf(pro.getId()));
            txtNombre.setText(pro.getNombre());
            txtDescripcion.setText(pro.getDescripcion());
            txtFechaIngreso.setDate(pro.getFecha_ing());
            
            ddlEstado.setSelectedIndex(cargarE(pro.getEstado()));
            txtSeguro.setText(String.valueOf(pro.getStk_seguro()));
            txtStockSucur.setText(String.valueOf(pro.getStk_sucur()));
            ddlRubro.setSelectedItem(pro.getRubro());
            txtValor.setText(String.valueOf(pro.getValor()));
            
            Empresa em = new Empresa();
            Sucursal suc = new Sucursal();
            suc = suc.buscar(pro.getId_sucur(), conn);
            em = em.buscar(suc.getEmpresaRut(), conn);
            ddlEmpresa2.getModel().setSelectedItem(em);
            ddlSucursal2.getModel().setSelectedItem(suc);
            
            btnNewProducto.setEnabled(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }else if(txtNombre.getText().equals("Ingrese ID del producto")){
            vistaDefault();
            lblRespuestaBuscar.setText("Ingrese ID antes de Buscar");
        }else{
            lblRespuestaBuscar.setText("No hay registros de la Sucursal con ID: " + txtBuscar.getText());
            vistaDefault();
        }
    }
    
    /**
     * Funcion que valida los campos de texto de acuerdo a las reglas de negocio
     * @return true o false dependiendo de si los campos de texto pasaron la prueba
     */
    private boolean validadorCampos() {
        boolean validar = true;
        if (txtNombre.getText().trim().isEmpty()) {
            validar = false;
        }
        if (txtDescripcion.getText().isEmpty()) {
            validar = false;
        }
        if (txtSeguro.getText().isEmpty()) {
            validar = false;
        }
        if (ddlRubro.getSelectedIndex() == 0) {
            validar = false;
        }
        if (txtValor.getText().isEmpty()) {
            validar = false;
        }if (txtFechaIngreso.getDate() == null) {
            validar = false;
        }
        if (txtStockSucur.getText().isEmpty()) {
            validar = false;
        }
        if (ddlRubro.getSelectedIndex() == 0) {
            validar = false;
        }
        if (ddlEmpresa2.getSelectedIndex() == 0) {
            validar = false;
        }

        if (ddlSucursal2.getSelectedIndex() == 0) {
            validar = false;
        }
        return validar;
    }

    /**
     * Funcion que capta lo que se seleccionar en el ddlestado
     * @return Recepciona un char representativo del estado en que se encuentra el producto 
     */
    private char cargarEstado() {
        char var = 0;
            if (ddlEstado.getSelectedIndex() == 0) {
                var = 'd';
            }else if (ddlEstado.getSelectedIndex() == 1) {
                var = 'f';
            }else if (ddlEstado.getSelectedIndex() == 2) {
                var = 'v';
            }
        return var;
    }

    /**
     * Funcion que carga el ddl estado de producto 
     * @param e estado del producto en la base de datos 
     * @return el numero del index el cual se cargara en el ddl 
     */
    private int cargarE(char e) {
        int index = 0;
            if (e == 'd') {
                index = 0;
            }else if (e == 'f'){
                index = 1;
            }else if (e == 'v'){
                index = 2;
            }
        return index;
    }
    
    /**
     * Funcion que valida que el sotck que se esta enviando sea valido
     * @param stock numero del stock de un producto 
     * @return true o false dependiendo de si el stock es mayor o menor a 0
     */
    public boolean validarStock(int stock){
        boolean validar = true;
        if (stock < 0) {
            validar = false;
        }
        return validar;
    }
    
    /**
     * Funcion que valida si el valor de un producto es mayor a 0 o no 
     * @param valor valor que se va a evaluar
     * @return true o false dependiendo de si el valor es mayor a 0 o no
     */
    public boolean validarValor(int valor){
        boolean validar = true;
        if (valor < 0) {
            validar = false;
        }
        return validar;
    }

    /**
     * Funcion que obtiene el rubro de un producto de acuerdo a lo que se alla seleccionado en el ddlRubro
     * @return Rubro del producto
     */
    private String obtenerRubro() {
        String rubro = "";
        switch (ddlRubro.getSelectedIndex()) {
            case 1:
                rubro = "Alimento";
                break;
            case 2:
                rubro = "Electronica";
                break;
            case 3:
                rubro = "Linea Blanca";
                break;
            case 4:
                rubro = "Vestuario";
                break;
            case 5:
                rubro = "Calzado";
                break;
        }
        return rubro;
    }

    /**
     * Funcion que obtiene la descripcion de un rubro de acuerdo a lo que se alla seleccionado en el ddlRubro
     * @return Descripcion del rubro
     */
    private String obtenerDescRubro() {
        String descRubro = "";
        switch (ddlRubro.getSelectedIndex()) {
            case 1:
                descRubro = "Sustancia normalmente ingeridas por seres vivos con fines nutricionales, sociales y psicológicos";
                break;
            case 2:
                descRubro = "Productos que consisten en una combinacion de componentes electronicos organizados en circuitos, destinaods "
                        + "a controlar y arovechar las señales electricas";
                break;
            case 3:
                descRubro = "Conjunto de distintos productos comerciales de un mismo tipo, generalmente de la misma marca, que tienen algunas características comunes que dan cierta unidad al conjunto.";
                break;
            case 4:
                descRubro = "refiere a las prendas de diferentes texturas fabricadas con diversas telas o pieles de animales, usadas por el ser humano para cubrir su cuerpo, incluyendo la ropa impermeable y otra para protegerse del clima adverso";
                break;
            case 5:
                descRubro = "Cualquier prenda de vestir que cubre y resguarda el pie y a veces también parte de la pierna.";
                break;
        }
        return descRubro;
    }

    
    /**
     * Método que carga la información del combobox de sucursales con la información asociada al rut de la empresa seleccionada
     * @param rut Rut asociado a la empresa seleccionada
     * @throws SQLException 
     */
    private void cargarSucursales(String rut) throws SQLException {
        ddlSucursal2.removeAllItems();
        ddlSucursal2.addItem("Seleccione la Sucursal");
        Sucursal suc = new Sucursal();
        ResultSet rs = suc.listadoSucursalesFiltro(conn, rut);
        while (rs.next()) {
            Sucursal v_suc = new Sucursal();
            v_suc.setId_sucur(rs.getInt("ID_SUCUR"));
            v_suc.setNombre(rs.getString("NOMBRE"));
            v_suc.setDireccion(rs.getString("DIRECCION"));
            v_suc.setComuna(rs.getString("COMUNA"));
            v_suc.setEmpresaRut(rs.getString("EMPRESA_RUT"));
            ddlSucursal2.addItem(v_suc);
        }
    }

    /**
     * Método que carga la información del combobox de empresas con la información registrada en la base de datos
     * @throws SQLException 
     */
    private void cargarEmpresas() throws SQLException {
        Empresa emp = new Empresa();
        ResultSet rs = emp.listadoEmpresas(conn);
        while (rs.next()) {
            Empresa v_emp = new Empresa();
            v_emp.setRut(rs.getString("RUT"));
            v_emp.setNombre(rs.getString("NOMBRE"));
            v_emp.setDireccion(rs.getString("DIRECCION"));
            v_emp.setRazon_social(rs.getString("RAZON_SOCIAL"));
            ddlEmpresa2.addItem(v_emp);
        }
    }

}
