DROP TABLE COMUNA;
CREATE TABLE COMUNA(
	ID NUMBER PRIMARY KEY,
	NOMBRE VARCHAR2 (50) NOT NULL,
	REGION VARCHAR2 (50) NOT NULL
);

INSERT INTO COMUNA VALUES (15101, 'Arica','Arica y Parinacota');
INSERT INTO COMUNA VALUES (15102, 'Camarones','Arica y Parinacota');
INSERT INTO COMUNA VALUES (15201, 'Putre','Arica y Parinacota');
INSERT INTO COMUNA VALUES (15202, 'General Lagos','Arica y Parinacota');
INSERT INTO COMUNA VALUES (1101, 'Iquique','Tarapaca');
INSERT INTO COMUNA VALUES (1402, 'Camina','Tarapaca');
INSERT INTO COMUNA VALUES (1403, 'Colchane','Tarapaca');
INSERT INTO COMUNA VALUES (1404, 'Huara','Tarapaca');
INSERT INTO COMUNA VALUES (1405, 'Pica','Tarapaca');
INSERT INTO COMUNA VALUES (1401, 'Pozo Almonte','Tarapaca');
INSERT INTO COMUNA VALUES (1107, 'Alto Hospicio','Tarapaca');
INSERT INTO COMUNA VALUES (2101, 'Antofagasta','Antofagasta');
INSERT INTO COMUNA VALUES (2102, 'Mejillones','Antofagasta');
INSERT INTO COMUNA VALUES (2103, 'Sierra Gorda','Antofagasta');
INSERT INTO COMUNA VALUES (2104, 'Taltal','Antofagasta');
INSERT INTO COMUNA VALUES (2201, 'Calama','Antofagasta');
INSERT INTO COMUNA VALUES (2202, 'Ollague','Antofagasta');
INSERT INTO COMUNA VALUES (2203, 'San Pedro Atacama','Antofagasta');
INSERT INTO COMUNA VALUES (2301, 'Tocopilla','Antofagasta');
INSERT INTO COMUNA VALUES (2302, 'Maria Elena','Antofagasta');
INSERT INTO COMUNA VALUES (3101, 'Copiapo','Atacama');
INSERT INTO COMUNA VALUES (3102, 'Caldera','Atacama');
INSERT INTO COMUNA VALUES (3103, 'Tierra Amarilla','Atacama');
INSERT INTO COMUNA VALUES (3201, 'Chanaral','Atacama');
INSERT INTO COMUNA VALUES (3202, 'Diego Almagro','Atacama');
INSERT INTO COMUNA VALUES (3301, 'Vallenar','Atacama');
INSERT INTO COMUNA VALUES (3302, 'Alto del Carmen','Atacama');
INSERT INTO COMUNA VALUES (3303, 'Freirina','Atacama');
INSERT INTO COMUNA VALUES (3304, 'Huasco','Atacama');
INSERT INTO COMUNA VALUES (4101, 'La Serena','Coquimbo');
INSERT INTO COMUNA VALUES (4102, 'Coquimbo','Coquimbo');
INSERT INTO COMUNA VALUES (4103, 'Andacollo','Coquimbo');
INSERT INTO COMUNA VALUES (4104, 'La Higuera','Coquimbo');
INSERT INTO COMUNA VALUES (4105, 'Paiguano','Coquimbo');
INSERT INTO COMUNA VALUES (4106, 'Vicuna','Coquimbo');
INSERT INTO COMUNA VALUES (4201, 'Illapel','Coquimbo');
INSERT INTO COMUNA VALUES (4202, 'Canela','Coquimbo');
INSERT INTO COMUNA VALUES (4203, 'Los Vilos','Coquimbo');
INSERT INTO COMUNA VALUES (4204, 'Salamanca','Coquimbo');
INSERT INTO COMUNA VALUES (4301, 'Ovalle','Coquimbo');
INSERT INTO COMUNA VALUES (4302, 'Combarbala','Coquimbo');
INSERT INTO COMUNA VALUES (4303, 'Monte Patria','Coquimbo');
INSERT INTO COMUNA VALUES (4304, 'Punitaqui','Coquimbo');
INSERT INTO COMUNA VALUES (4305, 'Rio Hurtado','Coquimbo');
INSERT INTO COMUNA VALUES (5101, 'Valparaiso','Valparaiso');
INSERT INTO COMUNA VALUES (5102, 'Casablanca','Valparaiso');
INSERT INTO COMUNA VALUES (5103, 'Concon','Valparaiso');
INSERT INTO COMUNA VALUES (5104, 'Juan Fernandez','Valparaiso');
INSERT INTO COMUNA VALUES (5105, 'Puchuncavi','Valparaiso');
INSERT INTO COMUNA VALUES (5801, 'Quilpue','Valparaiso');
INSERT INTO COMUNA VALUES (5107, 'Quintero','Valparaiso');
INSERT INTO COMUNA VALUES (5804, 'Villa Alemana','Valparaiso');
INSERT INTO COMUNA VALUES (5109, 'Vina del Mar','Valparaiso');
INSERT INTO COMUNA VALUES (5201, 'Isla  Pascua','Valparaiso');
INSERT INTO COMUNA VALUES (5301, 'Los Andes','Valparaiso');
INSERT INTO COMUNA VALUES (5302, 'Calle Larga','Valparaiso');
INSERT INTO COMUNA VALUES (5303, 'Rinconada','Valparaiso');
INSERT INTO COMUNA VALUES (5304, 'San Esteban','Valparaiso');
INSERT INTO COMUNA VALUES (5401, 'La Ligua','Valparaiso');
INSERT INTO COMUNA VALUES (5402, 'Cabildo','Valparaiso');
INSERT INTO COMUNA VALUES (5403, 'Papudo','Valparaiso');
INSERT INTO COMUNA VALUES (5404, 'Petorca','Valparaiso');
INSERT INTO COMUNA VALUES (5405, 'Zapallar','Valparaiso');
INSERT INTO COMUNA VALUES (5501, 'Quillota','Valparaiso');
INSERT INTO COMUNA VALUES (5502, 'Calera','Valparaiso');
INSERT INTO COMUNA VALUES (5503, 'Hijuelas','Valparaiso');
INSERT INTO COMUNA VALUES (5504, 'La Cruz','Valparaiso');
INSERT INTO COMUNA VALUES (5802, 'Limache','Valparaiso');
INSERT INTO COMUNA VALUES (5506, 'Nogales','Valparaiso');
INSERT INTO COMUNA VALUES (5803, 'Olmue','Valparaiso');
INSERT INTO COMUNA VALUES (5601, 'San Antonio','Valparaiso');
INSERT INTO COMUNA VALUES (5602, 'Algarrobo','Valparaiso');
INSERT INTO COMUNA VALUES (5603, 'Cartagena','Valparaiso');
INSERT INTO COMUNA VALUES (5604, 'El Quisco','Valparaiso');
INSERT INTO COMUNA VALUES (5605, 'El Tabo','Valparaiso');
INSERT INTO COMUNA VALUES (5606, 'Santo Domingo','Valparaiso');
INSERT INTO COMUNA VALUES (5701, 'San Felipe','Valparaiso');
INSERT INTO COMUNA VALUES (5702, 'Catemu','Valparaiso');
INSERT INTO COMUNA VALUES (5703, 'Llaillay','Valparaiso');
INSERT INTO COMUNA VALUES (5704, 'Panquehue','Valparaiso');
INSERT INTO COMUNA VALUES (5705, 'Putaendo','Valparaiso');
INSERT INTO COMUNA VALUES (5706, 'Santa Maria','Valparaiso');
INSERT INTO COMUNA VALUES (6101, 'Rancagua','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6102, 'Codegua','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6103, 'Coinco','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6104, 'Coltauco','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6105, 'Donihue','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6106, 'Graneros','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6107, 'Las Cabras','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6108, 'Machali','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6109, 'Malloa','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6110, 'Mostazal','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6111, 'Olivar','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6112, 'Peumo','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6113, 'Pichidegua','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6114, 'Quinta Tilcoco','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6115, 'Rengo','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6116, 'Requinoa','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6117, 'San Vicente','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6201, 'Pichilemu','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6202, 'La Estrella','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6203, 'Litueche','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6204, 'Marchihue','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6205, 'Navidad','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6206, 'Paredones','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6301, 'San Fernando','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6302, 'Chepica','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6303, 'Chimbarongo','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6304, 'Lolol','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6305, 'Nancagua','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6306, 'Palmilla','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6307, 'Peralillo','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6308, 'Placilla','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6309, 'Pumanque','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (6310, 'Santa Cruz','Del Libertador B. O Higgins');
INSERT INTO COMUNA VALUES (7101, 'Talca','Del Maule');
INSERT INTO COMUNA VALUES (7102, 'Constitucion','Del Maule');
INSERT INTO COMUNA VALUES (7103, 'Curepto','Del Maule');
INSERT INTO COMUNA VALUES (7104, 'Empedrado','Del Maule');
INSERT INTO COMUNA VALUES (7105, 'Maule','Del Maule');
INSERT INTO COMUNA VALUES (7106, 'Pelarco','Del Maule');
INSERT INTO COMUNA VALUES (7107, 'Pencahue','Del Maule');
INSERT INTO COMUNA VALUES (7108, 'Rio Claro','Del Maule');
INSERT INTO COMUNA VALUES (7109, 'San Clemente','Del Maule');
INSERT INTO COMUNA VALUES (7110, 'San Rafael','Del Maule');
INSERT INTO COMUNA VALUES (7201, 'Cauquenes','Del Maule');
INSERT INTO COMUNA VALUES (7202, 'Chanco','Del Maule');
INSERT INTO COMUNA VALUES (7203, 'Pelluhue','Del Maule');
INSERT INTO COMUNA VALUES (7301, 'Curico','Del Maule');
INSERT INTO COMUNA VALUES (7302, 'Hualane','Del Maule');
INSERT INTO COMUNA VALUES (7303, 'Licanten','Del Maule');
INSERT INTO COMUNA VALUES (7304, 'Molina','Del Maule');
INSERT INTO COMUNA VALUES (7305, 'Rauco','Del Maule');
INSERT INTO COMUNA VALUES (7306, 'Romeral','Del Maule');
INSERT INTO COMUNA VALUES (7307, 'Sagrada Familia','Del Maule');
INSERT INTO COMUNA VALUES (7308, 'Teno','Del Maule');
INSERT INTO COMUNA VALUES (7309, 'Vichuquen','Del Maule');
INSERT INTO COMUNA VALUES (7401, 'Linares','Del Maule');
INSERT INTO COMUNA VALUES (7402, 'Colbun','Del Maule');
INSERT INTO COMUNA VALUES (7403, 'Longavi','Del Maule');
INSERT INTO COMUNA VALUES (7404, 'Parral','Del Maule');
INSERT INTO COMUNA VALUES (7405, 'Retiro','Del Maule');
INSERT INTO COMUNA VALUES (7406, 'San Javier','Del Maule');
INSERT INTO COMUNA VALUES (7407, 'Villa Alegre','Del Maule');
INSERT INTO COMUNA VALUES (7408, 'Yerbas Buenas','Del Maule');
INSERT INTO COMUNA VALUES (8101, 'Concepcion','Del Biobio');
INSERT INTO COMUNA VALUES (8102, 'Coronel','Del Biobio');
INSERT INTO COMUNA VALUES (8103, 'Chiguayante','Del Biobio');
INSERT INTO COMUNA VALUES (8104, 'Florida','Del Biobio');
INSERT INTO COMUNA VALUES (8105, 'Hualqui','Del Biobio');
INSERT INTO COMUNA VALUES (8106, 'Lota','Del Biobio');
INSERT INTO COMUNA VALUES (8107, 'Penco','Del Biobio');
INSERT INTO COMUNA VALUES (8108, 'San Pedro la Paz','Del Biobio');
INSERT INTO COMUNA VALUES (8109, 'Santa Juana','Del Biobio');
INSERT INTO COMUNA VALUES (8110, 'Talcahuano','Del Biobio');
INSERT INTO COMUNA VALUES (8111, 'Tome','Del Biobio');
INSERT INTO COMUNA VALUES (8112, 'Hualpen','Del Biobio');
INSERT INTO COMUNA VALUES (8201, 'Lebu','Del Biobio');
INSERT INTO COMUNA VALUES (8202, 'Arauco','Del Biobio');
INSERT INTO COMUNA VALUES (8203, 'Canete','Del Biobio');
INSERT INTO COMUNA VALUES (8204, 'Contulmo','Del Biobio');
INSERT INTO COMUNA VALUES (8205, 'Curanilahue','Del Biobio');
INSERT INTO COMUNA VALUES (8206, 'Los alamos','Del Biobio');
INSERT INTO COMUNA VALUES (8207, 'Tirua','Del Biobio');
INSERT INTO COMUNA VALUES (8301, 'Los angeles','Del Biobio');
INSERT INTO COMUNA VALUES (8302, 'Antuco','Del Biobio');
INSERT INTO COMUNA VALUES (8303, 'Cabrero','Del Biobio');
INSERT INTO COMUNA VALUES (8304, 'Laja','Del Biobio');
INSERT INTO COMUNA VALUES (8305, 'Mulchen','Del Biobio');
INSERT INTO COMUNA VALUES (8306, 'Nacimiento','Del Biobio');
INSERT INTO COMUNA VALUES (8307, 'Negrete','Del Biobio');
INSERT INTO COMUNA VALUES (8308, 'Quilaco','Del Biobio');
INSERT INTO COMUNA VALUES (8309, 'Quilleco','Del Biobio');
INSERT INTO COMUNA VALUES (8310, 'San Rosendo','Del Biobio');
INSERT INTO COMUNA VALUES (8311, 'Santa Barbara','Del Biobio');
INSERT INTO COMUNA VALUES (8312, 'Tucapel','Del Biobio');
INSERT INTO COMUNA VALUES (8313, 'Yumbel','Del Biobio');
INSERT INTO COMUNA VALUES (8314, 'Alto Biobio','Del Biobio');
INSERT INTO COMUNA VALUES (8401, 'Chillan','Del Biobio');
INSERT INTO COMUNA VALUES (8402, 'Bulnes','Del Biobio');
INSERT INTO COMUNA VALUES (8403, 'Cobquecura','Del Biobio');
INSERT INTO COMUNA VALUES (8404, 'Coelemu','Del Biobio');
INSERT INTO COMUNA VALUES (8405, 'Coihueco','Del Biobio');
INSERT INTO COMUNA VALUES (8406, 'Chillan Viejo','Del Biobio');
INSERT INTO COMUNA VALUES (8407, 'El Carmen','Del Biobio');
INSERT INTO COMUNA VALUES (8408, 'Ninhue','Del Biobio');
INSERT INTO COMUNA VALUES (8409, 'niquen','Del Biobio');
INSERT INTO COMUNA VALUES (8410, 'Pemuco','Del Biobio');
INSERT INTO COMUNA VALUES (8411, 'Pinto','Del Biobio');
INSERT INTO COMUNA VALUES (8412, 'Portezuelo','Del Biobio');
INSERT INTO COMUNA VALUES (8413, 'Quillon','Del Biobio');
INSERT INTO COMUNA VALUES (8414, 'Quirihue','Del Biobio');
INSERT INTO COMUNA VALUES (8415, 'Ranquil','Del Biobio');
INSERT INTO COMUNA VALUES (8416, 'San Carlos','Del Biobio');
INSERT INTO COMUNA VALUES (8417, 'San Fabian','Del Biobio');
INSERT INTO COMUNA VALUES (8418, 'San Ignacio','Del Biobio');
INSERT INTO COMUNA VALUES (8419, 'San Nicolas','Del Biobio');
INSERT INTO COMUNA VALUES (8420, 'Treguaco','Del Biobio');
INSERT INTO COMUNA VALUES (8421, 'Yungay','Del Biobio');
INSERT INTO COMUNA VALUES (9101, 'Temuco','La Araucania');
INSERT INTO COMUNA VALUES (9102, 'Carahue','La Araucania');
INSERT INTO COMUNA VALUES (9103, 'Cunco','La Araucania');
INSERT INTO COMUNA VALUES (9104, 'Curarrehue','La Araucania');
INSERT INTO COMUNA VALUES (9105, 'Freire','La Araucania');
INSERT INTO COMUNA VALUES (9106, 'Galvarino','La Araucania');
INSERT INTO COMUNA VALUES (9107, 'Gorbea','La Araucania');
INSERT INTO COMUNA VALUES (9108, 'Lautaro','La Araucania');
INSERT INTO COMUNA VALUES (9109, 'Loncoche','La Araucania');
INSERT INTO COMUNA VALUES (9110, 'Melipeuco','La Araucania');
INSERT INTO COMUNA VALUES (9111, 'Nueva Imperial','La Araucania');
INSERT INTO COMUNA VALUES (9112, 'Padre Las Casas','La Araucania');
INSERT INTO COMUNA VALUES (9113, 'Perquenco','La Araucania');
INSERT INTO COMUNA VALUES (9114, 'Pitrufquen','La Araucania');
INSERT INTO COMUNA VALUES (9115, 'Pucon','La Araucania');
INSERT INTO COMUNA VALUES (9116, 'Saavedra','La Araucania');
INSERT INTO COMUNA VALUES (9117, 'Teodoro Schmidt','La Araucania');
INSERT INTO COMUNA VALUES (9118, 'Tolten','La Araucania');
INSERT INTO COMUNA VALUES (9119, 'Vilcun','La Araucania');
INSERT INTO COMUNA VALUES (9120, 'Villarrica','La Araucania');
INSERT INTO COMUNA VALUES (9121, 'Cholchol','La Araucania');
INSERT INTO COMUNA VALUES (9201, 'Angol','La Araucania');
INSERT INTO COMUNA VALUES (9202, 'Collipulli','La Araucania');
INSERT INTO COMUNA VALUES (9203, 'Curacautin','La Araucania');
INSERT INTO COMUNA VALUES (9204, 'Ercilla','La Araucania');
INSERT INTO COMUNA VALUES (9205, 'Lonquimay','La Araucania');
INSERT INTO COMUNA VALUES (9206, 'Los Sauces','La Araucania');
INSERT INTO COMUNA VALUES (9207, 'Lumaco','La Araucania');
INSERT INTO COMUNA VALUES (9208, 'Puren','La Araucania');
INSERT INTO COMUNA VALUES (9209, 'Renaico','La Araucania');
INSERT INTO COMUNA VALUES (9210, 'Traiguen','La Araucania');
INSERT INTO COMUNA VALUES (9211, 'Victoria','La Araucania');
INSERT INTO COMUNA VALUES (14101, 'Valdivia','Los Rios');
INSERT INTO COMUNA VALUES (14102, 'Corral','Los Rios');
INSERT INTO COMUNA VALUES (14202, 'Futrono','Los Rios');
INSERT INTO COMUNA VALUES (14201, 'La Union','Los Rios');
INSERT INTO COMUNA VALUES (14203, 'Lago Ranco','Los Rios');
INSERT INTO COMUNA VALUES (14103, 'Lanco','Los Rios');
INSERT INTO COMUNA VALUES (14104, 'Los Lagos','Los Rios');
INSERT INTO COMUNA VALUES (14105, 'Mafil','Los Rios');
INSERT INTO COMUNA VALUES (14106, 'Mariquina','Los Rios');
INSERT INTO COMUNA VALUES (14107, 'Paillaco','Los Rios');
INSERT INTO COMUNA VALUES (14108, 'Panguipulli','Los Rios');
INSERT INTO COMUNA VALUES (14204, 'Rio Bueno','Los Rios');
INSERT INTO COMUNA VALUES (10101, 'Puerto Montt','Los Lagos');
INSERT INTO COMUNA VALUES (10102, 'Calbuco','Los Lagos');
INSERT INTO COMUNA VALUES (10103, 'Cochamo','Los Lagos');
INSERT INTO COMUNA VALUES (10104, 'Fresia','Los Lagos');
INSERT INTO COMUNA VALUES (10105, 'Frutillar','Los Lagos');
INSERT INTO COMUNA VALUES (10106, 'Los Muermos','Los Lagos');
INSERT INTO COMUNA VALUES (10107, 'Llanquihue','Los Lagos');
INSERT INTO COMUNA VALUES (10108, 'Maullin','Los Lagos');
INSERT INTO COMUNA VALUES (10109, 'Puerto Varas','Los Lagos');
INSERT INTO COMUNA VALUES (10201, 'Castro','Los Lagos');
INSERT INTO COMUNA VALUES (10202, 'Ancud','Los Lagos');
INSERT INTO COMUNA VALUES (10203, 'Chonchi','Los Lagos');
INSERT INTO COMUNA VALUES (10204, 'Curaco Velez','Los Lagos');
INSERT INTO COMUNA VALUES (10205, 'Dalcahue','Los Lagos');
INSERT INTO COMUNA VALUES (10206, 'Puqueldon','Los Lagos');
INSERT INTO COMUNA VALUES (10207, 'Queilen','Los Lagos');
INSERT INTO COMUNA VALUES (10208, 'Quellon','Los Lagos');
INSERT INTO COMUNA VALUES (10209, 'Quemchi','Los Lagos');
INSERT INTO COMUNA VALUES (10210, 'Quinchao','Los Lagos');
INSERT INTO COMUNA VALUES (10301, 'Osorno','Los Lagos');
INSERT INTO COMUNA VALUES (10302, 'Puerto Octay','Los Lagos');
INSERT INTO COMUNA VALUES (10303, 'Purranque','Los Lagos');
INSERT INTO COMUNA VALUES (10304, 'Puyehue','Los Lagos');
INSERT INTO COMUNA VALUES (10305, 'Rio Negro','Los Lagos');
INSERT INTO COMUNA VALUES (10306, 'San Juan la Costa','Los Lagos');
INSERT INTO COMUNA VALUES (10307, 'San Pablo','Los Lagos');
INSERT INTO COMUNA VALUES (10401, 'Chaiten','Los Lagos');
INSERT INTO COMUNA VALUES (10402, 'Futaleufu','Los Lagos');
INSERT INTO COMUNA VALUES (10403, 'Hualaihue','Los Lagos');
INSERT INTO COMUNA VALUES (10404, 'Palena','Los Lagos');
INSERT INTO COMUNA VALUES (11101, 'Coihaique','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11102, 'Lago Verde','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11201, 'Aisen','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11202, 'Cisnes','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11203, 'Guaitecas','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11301, 'Cochrane','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11302, 'O Higgins','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11303, 'Tortel','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11401, 'Chile Chico','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (11402, 'Rio Ibanez','Aisen del Gral. C. Ibanez del Campo');
INSERT INTO COMUNA VALUES (12101, 'Punta Arenas','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12102, 'Laguna Blanca','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12103, 'Rio Verde','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12104, 'San Gregorio','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12201, 'Cabo Hornos','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12202, 'Antartica','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12301, 'Porvenir','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12302, 'Primavera','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12303, 'Timaukel','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12401, 'Natales','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (12402, 'Torres del Paine','Magallanes y La Antartica Chilena');
INSERT INTO COMUNA VALUES (13101, 'Santiago','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13102, 'Cerrillos','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13103, 'Cerro Navia','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13104, 'Conchali','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13105, 'El Bosque','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13106, 'Estacion Central','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13107, 'Huechuraba','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13108, 'Independencia','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13109, 'La Cisterna','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13110, 'La Florida','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13111, 'La Granja','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13112, 'La Pintana','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13113, 'La Reina','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13114, 'Las Condes','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13115, 'Lo Barnechea','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13116, 'Lo Espejo','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13117, 'Lo Prado','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13118, 'Macul','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13119, 'Maipu','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13120, 'nunoa','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13121, 'Pedro Aguirre Cerda','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13122, 'Penalolen','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13123, 'Providencia','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13124, 'Pudahuel','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13125, 'Quilicura','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13126, 'Quinta Normal','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13127, 'Recoleta','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13128, 'Renca','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13129, 'San Joaquin','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13130, 'San Miguel','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13131, 'San Ramon','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13132, 'Vitacura','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13201, 'Puente Alto','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13202, 'Pirque','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13203, 'San Jose Maipo','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13301, 'Colina','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13302, 'Lampa','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13303, 'Tiltil','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13401, 'San Bernardo','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13402, 'Buin','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13403, 'Calera Tango','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13404, 'Paine','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13501, 'Melipilla','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13502, 'Alhue','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13503, 'Curacavi','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13504, 'Maria Pinto','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13505, 'San Pedro','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13601, 'Talagante','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13602, 'El Monte','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13603, 'Isla Maipo','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13604, 'Padre Hurtado','Metropolitana Santiago');
INSERT INTO COMUNA VALUES (13605, 'Penaflor','Metropolitana Santiago');
