/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnlsGerente;

import MisPaquetes.Sucursal;
import static Sistema.MainSistema.conn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexi
 */
public class pnlReporteTiendas extends javax.swing.JPanel {

    /**
     * Creates new form ReporteTiendas
     */
    public pnlReporteTiendas() {  
        try {
            initComponents();
            cargarComboBox();
            vistaDefault();
        } catch (SQLException ex) {
            Logger.getLogger(pnlReporteTiendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnGenerarReporte = new javax.swing.JButton();
        cbxSucursal = new javax.swing.JComboBox<>();
        labelNombreTiendas1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JReporte = new javax.swing.JTable();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3), "Reporte de Tienda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setToolTipText("");

        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        cbxSucursal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una tienda" }));
        cbxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSucursalActionPerformed(evt);
            }
        });

        labelNombreTiendas1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombreTiendas1.setText("Tiendas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreTiendas1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnGenerarReporte)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNombreTiendas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        JReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Tienda", "Cantidad de usuarios", "Correos Enviados", "Cantidad de Valoraciones", " Descuentos por Rubro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        try {
            cargarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(pnlReporteTiendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void cbxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSucursalActionPerformed
       
    }//GEN-LAST:event_cbxSucursalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JReporte;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<Object> cbxSucursal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNombreTiendas1;
    // End of variables declaration//GEN-END:variables


    private void cargarComboBox() throws SQLException {
        Sucursal suc = new Sucursal();
        ResultSet rs = suc.listadoSucursales(conn);
        while (rs.next()) {
         Sucursal v_suc = new Sucursal();  
            v_suc.setId_sucur(rs.getInt("ID_SUCUR"));
            v_suc.setNombre(rs.getString("NOMBRE"));
            v_suc.setFono(rs.getString("FONO"));
            v_suc.setDireccion(rs.getString("DIRECCION"));
            v_suc.setComuna(rs.getString("COMUNA"));
            v_suc.setEmpresaRut(rs.getString("EMPRESA_RUT"));
            cbxSucursal.addItem(v_suc);
        }
    }
    

    private void vistaDefault() {
        cbxSucursal.setEnabled(true);
        btnGenerarReporte.setEnabled(true);
        JReporte.setEnabled(true);
    }
  
    private void cargarTabla() throws SQLException {
        DefaultTableModel modelo =  new DefaultTableModel();
            modelo.addColumn("Nombre");   
            modelo.addColumn("Cantidad Usuarios");
            modelo.addColumn("Mensajes");   
            modelo.addColumn("Valoracion");
            modelo.addColumn("Descuentos Por rubro");
            Sucursal suc = new Sucursal();
            ResultSet rs = suc.reporteSucursal(conn, cbxSucursal.getSelectedIndex());
            Object [] fila = new Object[5];
            while(rs.next()){
                fila[0] = rs.getString("nombre");
                fila[1] = rs.getString("nro_usuarios");
                fila[2] = rs.getString("mensajes");
                fila[3] = rs.getString("valoracion");
                fila[4] = rs.getString("desc_rubro");
                modelo.addRow(fila);
            }
            
            JReporte.setModel(modelo);
            JReporte.setVisible(true);
    }
       
}
